#!/usr/bin/env php
<?php

/*
 * Usage: ./kohana <controler>(/<action>(/<id>)) [--option1=optval1 --option2=optval2]
 * Example: ./kohana sebicas/view --username=john --password=secret --name="John Doe"
 */

// Define Paths
define('INDEX', '../../public_html/index.php');
define('PHP_BIN', '/usr/bin/php');

// Count Arguments
$args = count($argv) - 1;

if($args < 1)
{
    echo "\nKohana - CLI Reloaded v0.1 beta";
    echo "\nhttps://github.com/sebicas";
    echo "\n\nError: Please set URI\nExample: $ kohana <controler>(/<action>(/<id>)) [--option1=optval1 --option2=optval2]\n\n";
}
 else
{
    // Set Command
    $cmd = PHP_BIN.' '.INDEX.' --uri=';

    for ($i = 1; $i <= $args; $i++)
    {
        $cmd .= $argv[$i].' ';
    }

    // Execute Kohana
    passthru($cmd);
}